### PR TITLE
React Navigation Modal Fix

### LINKED ISSUE #41: Not able to move crop overlay on Android devices.
It is not possible to move or change the size of the crop overlay on Android devices. I tested this on Samsung s20FE and Pixel 3a both running Android 11. Can you please check this issue on your side? The editor is working fine on iOS devices.

### PR DESCRIPTION
**Pull request by thomas-coldwell**
- Closes #41 due to linked issue https://github.com/react-navigation/react-navigation/issues/9757 by exporting a `<ImageEditorView />` without the modal that can then be used in a Stack Modal using React Navigation

### CODE REVIEW

**Comment by DeWulfJerome** [comment]
Just opened an issue on this, my bad!
Any idea when you'll have the time to publish this?

Great work btw

**Comment by thomas-coldwell** [comment]
Thanks dude! Sorry I haven't had a chance to update the docs (will do shortly). If you use the component and add the the prop `asView` you can render it in a Stack Modal.

I've just discovered a bit of a new work around today which might be way better using portals:
https://github.com/react-navigation/react-navigation/issues/9757#issuecomment-890354731

Will try update the library shortly to include this behaviour as it makes it less specific to React Navigation 😀

**Comment by thomas-coldwell** [comment]
I've updated the docs now to show this! Feel feel to give it a try and if it still gives you any trouble do let me know :) https://github.com/thomas-coldwell/expo-image-editor/issues/41#issuecomment-893396255

**Comment by DeWulfJerome** [comment]
Thanks man! 👏 I'm on holiday now but will give it a try in 2 weeks.

**Pull request merged**
